### ISSUE TITLE
 IaphubDataProvider onPurchase and onError not triggered

### ISSUE THREAD

**Issue by ryan-granlund** [iaphub/react-native-iaphub-ui#1]
After a successful IAP, onPurchase is not being called.

    "react-native-iaphub": "^8.1.4",
    "react-native-iaphub-ui": "^1.0.1",

<IaphubDataProvider
      appId="xxx"
      apiKey="xxx"
      lang="en"
      allowAnonymousPurchase={true}
      onPurchase={() => {purchaseSuccess()}}
      onError={() => {purchaseError()}}>

Originally I was using onByeEnd in the IaphubDataConsumer but I realized that triggers even if the user cancels the IAP transaction. Is there a way to tell if the the transaction was successful other than using onPurchase?

**Comment by iaphub** [comment]
Hi @ryan-granlund,
Just checked and the `onPurchase` event does work, your code looks incorrect.

```jsx
<IaphubDataProvider
appId="xxx"
apiKey="xxx"
lang="en"
allowAnonymousPurchase={true}
onPurchase={(transaction) => console.log('transaction: ', transaction)}
onError={(err) => console.log('Error: ', err)}>
```
Also you can use the `onBuyEnd` event as well, it takes 2 arguments in parameter:  `err`, `transaction`.
You can check the error in order to filter errors.

**Comment by ryan-granlund** [comment]
Ahhh yes you are correct. I was able to use onBuyEnd and if err is null, I know the transaction was successful. 

Thanks for the help!!
