### ISSUE TITLE
Doesn't display productsForSale

### ISSUE THREAD

**Issue by nartydev** [iaphub/react-native-iaphub-ui#3]
Hi, I try to use the component `PaywallSubscriptionGroup` like example I have something like this:
```JS
     <IaphubDataConsumer>
        {iaphubData => (
            <PaywallSubscriptionGroup
              {...iaphubData}
            />
      )}
   </IaphubDataConsumer>
```
I do receive the productsForSale from the store so I don't understand why it is not displayed
I have try on simulator and on device on iOS, that doesn't work also on TestFlight

<img width="343" alt="image" src="https://user-images.githubusercontent.com/16448382/221434265-3c55dffb-4b2a-45ef-a500-7ad8554cd8e4.png">

**Comment by iaphub** [comment]
Hi @nartydev,
I'm sorry but we were not able to reproduce your issue. Are you using the `IaphubDataProvider` component?
What is the data returned by the `IaphubDataConsumer`? (if you add  `console.log(iaphubData)`).
