### ISSUE TITLE
Please check and fix.

### ISSUE THREAD

**Issue by BaiXiaoYan** [iaphub/react-native-iaphub-ui#6]
Hi, iaphub
Seems the code has some issues.
Please check below image.
![image](https://github.com/iaphub/react-native-iaphub-ui/assets/12760348/0f3492c8-d764-4345-9d05-dfbaaeea723b)

I think it should be like below.
...
Buy={(Buy=== undefined) ? DefaultBuy: Buy}
...

I'm waiting for fixing this issue asap.
thank you.

**Comment by iaphub** [comment]
Thanks for the feedback, the issue has been fixed in the latest version (1.2.4)
